# Generated by Django 5.1.7 on 2025-03-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Category',
            new_name='category',
        ),
    ]
