# Generated by Django 5.1.7 on 2025-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(help_text='图片尺寸1：1', upload_to='team', verbose_name='头像')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(max_length=100, verbose_name='职务')),
                ('rank', models.IntegerField(verbose_name='排序')),
            ],
        ),
    ]
