# Generated by Django 5.1.7 on 2025-03-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '团队管理', 'verbose_name_plural': '团队管理'},
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
