# Generated by Django 5.1.7 on 2025-03-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_options_alter_team_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='position',
        ),
    ]
